site_name: AGU20-OS022-08
theme:
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 3
    - admonition
    - codehilite
    - mkautodoc
nav:
    - Home: README.md
    - API: api.md
plugins:
  - mkdocstrings
  - search
