site_name: AGU20-OS022-08
theme:
    name: material
markdown_extensions:
    - toc:
        permalink: "#"
        baselevel: 3
    - admonition
    - codehilite
    - mkautodoc
nav:
    - Index: index.md
    - Home: README.md
    - API: api.md
plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
  - search
