name: python

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # OS to run the tests on

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest
          if [ -f requirements/test-requirements.txt ]; then pip install -r requirements/test-requirements.txt; fi
      - name: Lint with pylint
        run: |
          # lint with the rules defined in pylintrc
          pylint --ignore-patterns=lint_test src
