name: website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings
      - run: pip install mkautodoc
      - run: pip install -e .
      - run: pip install requirements/requirements.txt
      - run: mkdocs gh-deploy --force
